### ISSUE TITLE
Add `repr(transparent)` to VolatileCell

### ISSUE THREAD

**Issue by garasubo** [japaric/vcell#5]
`repr(tranparent)` guarantees the same layout and ABI as one single field for the struct with a single field. So, we can guarantee `VolatileCell<T>` layout and ABI as `T`.

This struct is already used in the code generated by svd2rust and it is ABI sensitive because it is used in structs with `repr(C)`.

**Comment by therealprof** [comment]
@japaric This seems very useful to have.

**Comment by Sympatron** [comment]
What is the current state here? I was quite surprised, that `VolatileCell` is not `repr(transparent)`, because that means relying on `VolatileCell<T>` to have the same ABI as `T` is UB at the moment.

There is already a PR for this: #6

**Comment by korken89** [comment]
Merged and published in `v0.1.3`
